spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          clientId: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
